contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #immunogenomics channel"
    url: https://nfcore.slack.com/channels/immunogenomics
    about: Discussion about the nf-core/immunogenomics pipeline
